layout_spectrum: 0
typography_spectrum: 0.1403509
color:
  saturation: 0.8271057
  lightness: 0.656377
  brandStrength: 0.4887218
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#00A652'
    - '#444444'
    - '#A4A7AE'
  rhythmicContrast: 0.4650121
name: RUTA AUTO COUNSULTING
